// features/product/viewmodel/useProductDetailViewModel.ts
import { useState, useCallback, useMemo } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { useCart } from '../../../services/CartContext';

export interface ProductDetail {
  id: string;
  name: string;
  farmer: string;
  farmerRating: number;
  price: number;
  unit: string;
  description: string;
  category: string;
  rating: number;
  reviewCount: number;
  isOrganic: boolean;
  inStock: boolean;
  stockAmount: string;
  images: string[];
}

// Mock product data (TODO: replace with API call)
const MOCK_PRODUCTS: Record<string, ProductDetail> = {
  p1: {
    id: 'p1',
    name: 'Organic Sukuma Wiki',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.8,
    price: 2500,
    unit: 'bunch',
    description: 'Freshly harvested organic sukuma wiki (collard greens) from our family farm in Wakiso. Grown without synthetic pesticides or fertilizers. Harvested this morning for maximum freshness.',
    category: 'vegetables',
    rating: 4.8,
    reviewCount: 42,
    isOrganic: true,
    inStock: true,
    stockAmount: '50+ bunches available',
    images: [],
  },
  p2: {
    id: 'p2',
    name: 'Fresh Matoke',
    farmer: 'Kampala Greens',
    farmerRating: 4.6,
    price: 5000,
    unit: 'kg',
    description: 'Green cooking bananas (matoke) from the fertile slopes of Mt. Elgon. Perfect for your traditional Ugandan meals.',
    category: 'vegetables',
    rating: 4.6,
    reviewCount: 28,
    isOrganic: false,
    inStock: true,
    stockAmount: '30 kg available',
    images: [],
  },
  p3: {
    id: 'p3',
    name: 'Ripe Avocados',
    farmer: 'Kayunga Organics',
    farmerRating: 4.9,
    price: 3000,
    unit: 'each',
    description: 'Large, creamy Hass avocados from Kayunga. Organically grown and tree-ripened for the perfect buttery texture.',
    category: 'fruits',
    rating: 4.9,
    reviewCount: 56,
    isOrganic: true,
    inStock: true,
    stockAmount: '20+ available',
    images: [],
  },
  p4: {
    id: 'p4',
    name: 'Free-Range Eggs (tray)',
    farmer: 'Mukono Poultry',
    farmerRating: 4.7,
    price: 8000,
    unit: 'tray',
    description: 'Farm-fresh free-range eggs from happy chickens raised on open pastures in Mukono. Rich orange yolks, perfect for any recipe.',
    category: 'dairy_eggs',
    rating: 4.7,
    reviewCount: 35,
    isOrganic: true,
    inStock: true,
    stockAmount: '15 trays available',
    images: [],
  },
  p5: {
    id: 'p5',
    name: 'Sweet Bananas',
    farmer: 'Kayunga Organics',
    farmerRating: 4.7,
    price: 2000,
    unit: 'bunch',
    description: 'Sweet, ripe bananas freshly harvested from the Kayunga organic farm. Naturally ripened for the perfect sweetness.',
    category: 'fruits',
    rating: 4.5,
    reviewCount: 19,
    isOrganic: false,
    inStock: true,
    stockAmount: '10 bunches Available',
    images: [],
  },
  p6: {
    id: 'p6',
    name: 'Groundnuts (1kg)',
    farmer: 'Gulu Grains',
    farmerRating: 4.4,
    price: 6000,
    unit: 'kg',
    description: 'Premium quality groundnuts from northern Uganda. Perfect for making groundnut sauce or roasting as a snack.',
    category: 'grains',
    rating: 4.4,
    reviewCount: 23,
    isOrganic: true,
    inStock: true,
    stockAmount: '25 kg available',
    images: [],
  },
  p7: {
    id: 'p7',
    name: 'Fresh Tilapia',
    farmer: 'Jinja Fish Farms',
    farmerRating: 4.9,
    price: 12000,
    unit: 'kg',
    description: 'Fresh Nile tilapia from the shores of Lake Victoria. Caught daily and delivered fresh to your doorstep.',
    category: 'fish_meat',
    rating: 4.9,
    reviewCount: 67,
    isOrganic: false,
    inStock: true,
    stockAmount: '10 kg available',
    images: [],
  },
  p8: {
    id: 'p8',
    name: 'Local Chicken',
    farmer: 'Mukono Poultry',
    farmerRating: 4.8,
    price: 25000,
    unit: 'whole',
    description: 'Free-range local chicken raised on natural feeds. Perfect for soup or roasted chicken.',
    category: 'fish_meat',
    rating: 4.8,
    reviewCount: 44,
    isOrganic: true,
    inStock: true,
    stockAmount: '5 available',
    images: [],
  },
  p9: {
    id: 'p9',
    name: 'Posho (Maize Flour)',
    farmer: 'Gulu Grains',
    farmerRating: 4.3,
    price: 3500,
    unit: 'kg',
    description: 'Finely milled maize flour from Gulu. Perfect for making ugali/posho. Stone-ground for the best texture.',
    category: 'grains',
    rating: 4.3,
    reviewCount: 31,
    isOrganic: false,
    inStock: true,
    stockAmount: '100 kg available',
    images: [],
  },
  p10: {
    id: 'p10',
    name: 'Fresh Ginger',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.6,
    price: 1500,
    unit: 'piece',
    description: 'Aromatic fresh ginger root from local farms. Adds a wonderful kick to your tea, stews, and sauces.',
    category: 'herbs',
    rating: 4.6,
    reviewCount: 15,
    isOrganic: true,
    inStock: true,
    stockAmount: '30+ pieces available',
    images: [],
  },
  p11: {
    id: 'p11',
    name: 'Organic Tomatoes',
    farmer: 'Kayunga Organics',
    farmerRating: 4.7,
    price: 4000,
    unit: 'kg',
    description: 'Vine-ripened organic tomatoes bursting with flavor. Grown without synthetic pesticides in the fertile soils of Kayunga.',
    category: 'vegetables',
    rating: 4.7,
    reviewCount: 38,
    isOrganic: true,
    inStock: true,
    stockAmount: '20 kg available',
    images: [],
  },
  p12: {
    id: 'p12',
    name: 'Fresh Milk (1L)',
    farmer: 'Mbarara Dairy',
    farmerRating: 4.8,
    price: 5000,
    unit: 'litre',
    description: 'Pure fresh milk from the lush pastures of Mbarara. Pasteurized for safety, full cream for the best taste.',
    category: 'dairy_eggs',
    rating: 4.8,
    reviewCount: 52,
    isOrganic: false,
    inStock: true,
    stockAmount: '50 litres available',
    images: [],
  },
  p13: {
    id: 'p13',
    name: 'Fresh Cabbage',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.5,
    price: 3000,
    unit: 'each',
    description: 'Crisp, fresh cabbages harvested at peak freshness. Great for salads, coleslaw, or cooked dishes.',
    category: 'vegetables',
    rating: 4.5,
    reviewCount: 31,
    isOrganic: false,
    inStock: true,
    stockAmount: '20+ available',
    images: [],
  },
  p14: {
    id: 'p14',
    name: 'Broccoli',
    farmer: 'Kampala Greens',
    farmerRating: 4.3,
    price: 5000,
    unit: 'kg',
    description: 'Fresh green broccoli florets grown in the cool highlands. Packed with vitamins and antioxidants.',
    category: 'vegetables',
    rating: 4.3,
    reviewCount: 18,
    isOrganic: true,
    inStock: true,
    stockAmount: '10 kg available',
    images: [],
  },
  p15: {
    id: 'p15',
    name: 'Sweet Corn',
    farmer: 'Gulu Grains',
    farmerRating: 4.6,
    price: 2000,
    unit: 'each',
    description: 'Fresh sweet corn on the cob. Perfect for boiling, grilling, or roasting. Naturally sweet and juicy.',
    category: 'vegetables',
    rating: 4.6,
    reviewCount: 25,
    isOrganic: false,
    inStock: true,
    stockAmount: '30+ available',
    images: [],
  },
  p16: {
    id: 'p16',
    name: 'Green Beans',
    farmer: 'Kayunga Organics',
    farmerRating: 4.4,
    price: 3500,
    unit: 'kg',
    description: 'Fresh, crisp green beans from organic farms. Perfect as a side dish or in stir-fries.',
    category: 'vegetables',
    rating: 4.4,
    reviewCount: 21,
    isOrganic: true,
    inStock: true,
    stockAmount: '15 kg available',
    images: [],
  },
  p17: {
    id: 'p17',
    name: 'Fresh Mangoes',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.7,
    price: 3500,
    unit: 'kg',
    description: 'Sweet, juicy mangoes from eastern Uganda. Tree-ripened for maximum sweetness.',
    category: 'fruits',
    rating: 4.7,
    reviewCount: 33,
    isOrganic: false,
    inStock: true,
    stockAmount: '25 kg available',
    images: [],
  },
  p18: {
    id: 'p18',
    name: 'Pineapple',
    farmer: 'Kayunga Organics',
    farmerRating: 4.8,
    price: 5000,
    unit: 'each',
    description: 'Sweet organic pineapples from Kayunga. Naturally grown, incredibly sweet and juicy.',
    category: 'fruits',
    rating: 4.8,
    reviewCount: 41,
    isOrganic: true,
    inStock: true,
    stockAmount: '15 available',
    images: [],
  },
  p19: {
    id: 'p19',
    name: 'Watermelon',
    farmer: 'Kampala Greens',
    farmerRating: 4.5,
    price: 8000,
    unit: 'each',
    description: 'Large, juicy watermelons perfect for hot days. Refreshing and naturally sweet.',
    category: 'fruits',
    rating: 4.5,
    reviewCount: 27,
    isOrganic: false,
    inStock: true,
    stockAmount: '10 available',
    images: [],
  },
  p20: {
    id: 'p20',
    name: 'Oranges',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.4,
    price: 3000,
    unit: 'kg',
    description: 'Fresh citrus oranges from local farms. Perfect for fresh juice or eating fresh.',
    category: 'fruits',
    rating: 4.4,
    reviewCount: 22,
    isOrganic: false,
    inStock: true,
    stockAmount: '30 kg available',
    images: [],
  },
  p21: {
    id: 'p21',
    name: 'Lemons',
    farmer: 'Kayunga Organics',
    farmerRating: 4.3,
    price: 1500,
    unit: 'piece',
    description: 'Organic lemons grown without chemicals. Great for tea, cooking, and fresh lemonade.',
    category: 'fruits',
    rating: 4.3,
    reviewCount: 15,
    isOrganic: true,
    inStock: true,
    stockAmount: '40+ available',
    images: [],
  },
  p22: {
    id: 'p22',
    name: 'Cheese Block',
    farmer: 'Mbarara Dairy',
    farmerRating: 4.6,
    price: 12000,
    unit: 'kg',
    description: 'Premium quality cheese from Mbarara Dairy. Made from fresh cows milk. Perfect for sandwiches and cooking.',
    category: 'dairy_eggs',
    rating: 4.6,
    reviewCount: 18,
    isOrganic: false,
    inStock: true,
    stockAmount: '5 kg available',
    images: [],
  },
  p23: {
    id: 'p23',
    name: 'Yogurt',
    farmer: 'Mbarara Dairy',
    farmerRating: 4.5,
    price: 4000,
    unit: 'cup',
    description: 'Creamy yogurt made from fresh Mbarara milk. Rich in probiotics and natural goodness.',
    category: 'dairy_eggs',
    rating: 4.5,
    reviewCount: 29,
    isOrganic: false,
    inStock: true,
    stockAmount: '20 cups available',
    images: [],
  },
  p24: {
    id: 'p24',
    name: 'Farm Fresh Butter',
    farmer: 'Mbarara Dairy',
    farmerRating: 4.7,
    price: 7000,
    unit: 'kg',
    description: 'Rich, creamy butter churned from fresh cream. Perfect for baking and cooking.',
    category: 'dairy_eggs',
    rating: 4.7,
    reviewCount: 14,
    isOrganic: true,
    inStock: true,
    stockAmount: '8 kg available',
    images: [],
  },
  p25: {
    id: 'p25',
    name: 'Organic Eggs (6)',
    farmer: 'Mukono Poultry',
    farmerRating: 4.6,
    price: 4500,
    unit: 'pack',
    description: 'Pack of 6 organic free-range eggs. Rich orange yolks from happy, free-roaming chickens.',
    category: 'dairy_eggs',
    rating: 4.6,
    reviewCount: 23,
    isOrganic: true,
    inStock: true,
    stockAmount: '20 packs available',
    images: [],
  },
  p26: {
    id: 'p26',
    name: 'Rice',
    farmer: 'Gulu Grains',
    farmerRating: 4.5,
    price: 5000,
    unit: 'kg',
    description: 'Premium long-grain rice grown in the fertile plains of eastern Uganda. Perfect for daily meals.',
    category: 'grains',
    rating: 4.5,
    reviewCount: 28,
    isOrganic: false,
    inStock: true,
    stockAmount: '100 kg available',
    images: [],
  },
  p27: {
    id: 'p27',
    name: 'Sorghum Flour',
    farmer: 'Gulu Grains',
    farmerRating: 4.2,
    price: 4000,
    unit: 'kg',
    description: 'Nutritious sorghum flour from northern Uganda. Perfect for making traditional porridge and bread.',
    category: 'grains',
    rating: 4.2,
    reviewCount: 12,
    isOrganic: true,
    inStock: true,
    stockAmount: '30 kg available',
    images: [],
  },
  p28: {
    id: 'p28',
    name: 'Millet Flour',
    farmer: 'Gulu Grains',
    farmerRating: 4.3,
    price: 4500,
    unit: 'kg',
    description: 'Finely ground millet flour from organic farms. Rich in iron and fiber. Ideal for nutritious porridge.',
    category: 'grains',
    rating: 4.3,
    reviewCount: 16,
    isOrganic: true,
    inStock: true,
    stockAmount: '25 kg available',
    images: [],
  },
  p29: {
    id: 'p29',
    name: 'Beans',
    farmer: 'Gulu Grains',
    farmerRating: 4.5,
    price: 5000,
    unit: 'kg',
    description: 'Premium dried beans from northern Uganda. High in protein and fiber. Perfect for stews and soups.',
    category: 'grains',
    rating: 4.5,
    reviewCount: 34,
    isOrganic: false,
    inStock: true,
    stockAmount: '40 kg available',
    images: [],
  },
  p30: {
    id: 'p30',
    name: 'Beef (1kg)',
    farmer: 'Mbarara Dairy',
    farmerRating: 4.6,
    price: 15000,
    unit: 'kg',
    description: 'Premium beef from grass-fed cattle in Mbarara. Tender and flavorful, perfect for stews and roasts.',
    category: 'fish_meat',
    rating: 4.6,
    reviewCount: 37,
    isOrganic: false,
    inStock: true,
    stockAmount: '15 kg available',
    images: [],
  },
  p31: {
    id: 'p31',
    name: 'Pork (1kg)',
    farmer: 'Mukono Poultry',
    farmerRating: 4.4,
    price: 12000,
    unit: 'kg',
    description: 'Fresh pork from locally raised pigs. Perfect for roasting, frying, or making stews.',
    category: 'fish_meat',
    rating: 4.4,
    reviewCount: 19,
    isOrganic: false,
    inStock: true,
    stockAmount: '10 kg available',
    images: [],
  },
  p32: {
    id: 'p32',
    name: 'Mukene',
    farmer: 'Jinja Fish Farms',
    farmerRating: 4.5,
    price: 8000,
    unit: 'kg',
    description: 'Dried silver cyprinid (mukene) from Lake Victoria. Rich in protein, perfect for adding flavor to sauces and stews.',
    category: 'fish_meat',
    rating: 4.5,
    reviewCount: 26,
    isOrganic: false,
    inStock: true,
    stockAmount: '20 kg available',
    images: [],
  },
  p33: {
    id: 'p33',
    name: 'Grasshoppers (Nsenene)',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.7,
    price: 10000,
    unit: 'kg',
    description: 'Seasonal grasshoppers (nsenene), a Ugandan delicacy. Deep-fried to crispy perfection. Rich in protein.',
    category: 'fish_meat',
    rating: 4.7,
    reviewCount: 33,
    isOrganic: true,
    inStock: true,
    stockAmount: '5 kg available',
    images: [],
  },
  p34: {
    id: 'p34',
    name: 'Garlic',
    farmer: 'Kayunga Organics',
    farmerRating: 4.5,
    price: 2000,
    unit: 'piece',
    description: 'Organic garlic bulbs from Kayunga. Pungent and flavorful, essential for any kitchen.',
    category: 'herbs',
    rating: 4.5,
    reviewCount: 21,
    isOrganic: true,
    inStock: true,
    stockAmount: '30+ pieces available',
    images: [],
  },
  p35: {
    id: 'p35',
    name: 'Fresh Dill',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.3,
    price: 1000,
    unit: 'bunch',
    description: 'Fresh dill from local farms. Adds a unique flavor to fish dishes, salads, and pickles.',
    category: 'herbs',
    rating: 4.3,
    reviewCount: 8,
    isOrganic: true,
    inStock: true,
    stockAmount: '15 bunches available',
    images: [],
  },
  p36: {
    id: 'p36',
    name: 'Cloves',
    farmer: 'Kayunga Organics',
    farmerRating: 4.4,
    price: 3000,
    unit: 'pack',
    description: 'Aromatic cloves perfect for spicing up your dishes and teas. Known for their warm, sweet flavor.',
    category: 'herbs',
    rating: 4.4,
    reviewCount: 12,
    isOrganic: false,
    inStock: true,
    stockAmount: '20 packs available',
    images: [],
  },
  p37: {
    id: 'p37',
    name: 'Cinnamon Sticks',
    farmer: 'Mama Mboga Farm',
    farmerRating: 4.2,
    price: 2500,
    unit: 'pack',
    description: 'Premium cinnamon sticks for cooking, baking, and tea. Rich, warm flavor that enhances any dish.',
    category: 'herbs',
    rating: 4.2,
    reviewCount: 10,
    isOrganic: false,
    inStock: true,
    stockAmount: '15 packs available',
    images: [],
  },
  p38: {
    id: 'p38',
    name: 'Dried Beans',
    farmer: 'Gulu Grains',
    farmerRating: 4.5,
    price: 5000,
    unit: 'kg',
    description: 'Premium dried beans from organic farms in northern Uganda. Rich in protein and fiber.',
    category: 'legumes',
    rating: 4.5,
    reviewCount: 28,
    isOrganic: true,
    inStock: true,
    stockAmount: '40 kg available',
    images: [],
  },
  p39: {
    id: 'p39',
    name: 'Cowpeas',
    farmer: 'Gulu Grains',
    farmerRating: 4.3,
    price: 4500,
    unit: 'kg',
    description: 'Nutritious cowpeas from northern Uganda. High in protein, perfect for traditional stews.',
    category: 'legumes',
    rating: 4.3,
    reviewCount: 16,
    isOrganic: false,
    inStock: true,
    stockAmount: '20 kg available',
    images: [],
  },
  p40: {
    id: 'p40',
    name: 'Soybeans',
    farmer: 'Gulu Grains',
    farmerRating: 4.2,
    price: 4000,
    unit: 'kg',
    description: 'Premium soybeans from organic farms. Rich in protein, perfect for making soymilk and other dishes.',
    category: 'legumes',
    rating: 4.2,
    reviewCount: 14,
    isOrganic: true,
    inStock: true,
    stockAmount: '25 kg available',
    images: [],
  },
  p41: {
    id: 'p41',
    name: 'Peas',
    farmer: 'Kayunga Organics',
    farmerRating: 4.4,
    price: 6000,
    unit: 'kg',
    description: 'Fresh green peas from organic farms. Sweet and tender, perfect for stews and side dishes.',
    category: 'legumes',
    rating: 4.4,
    reviewCount: 19,
    isOrganic: true,
    inStock: true,
    stockAmount: '15 kg available',
    images: [],
  },
  p42: {
    id: 'p42',
    name: 'Lentils',
    farmer: 'Gulu Grains',
    farmerRating: 4.6,
    price: 7000,
    unit: 'kg',
    description: 'Premium red lentils from northern Uganda. Quick-cooking and packed with protein and nutrients.',
    category: 'legumes',
    rating: 4.6,
    reviewCount: 22,
    isOrganic: false,
    inStock: true,
    stockAmount: '18 kg available',
    images: [],
  },
};

export interface UseProductDetailViewModelReturn {
  product: ProductDetail | null;
  quantity: number;
  isLoading: boolean;
  onIncreaseQuantity: () => void;
  onDecreaseQuantity: () => void;
  onAddToCart: () => void;
  onBack: () => void;
}

export function useProductDetailViewModel(): UseProductDetailViewModelReturn {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [quantity, setQuantity] = useState(1);
  const [isLoading] = useState(false);

  const product = useMemo(() => {
    if (!id) return null;
    return MOCK_PRODUCTS[id] ?? null;
  }, [id]);

  const onIncreaseQuantity = useCallback(() => {
    setQuantity((prev) => Math.min(prev + 1, 20));
  }, []);

  const onDecreaseQuantity = useCallback(() => {
    setQuantity((prev) => Math.max(prev - 1, 1));
  }, []);

  const { addItem } = useCart();

  const onAddToCart = useCallback(() => {
    if (!product) return;
    addItem({
      productId: product.id,
      name: product.name,
      price: product.price,
      unit: product.unit,
      quantity,
      farmer: product.farmer,
      category: product.category,
    });
    router.back();
  }, [product, quantity, addItem]);

  const onBack = useCallback(() => {
    router.back();
  }, []);

  return {
    product,
    quantity,
    isLoading,
    onIncreaseQuantity,
    onDecreaseQuantity,
    onAddToCart,
    onBack,
  };
}